### ISSUE TITLE
small bug in v2.3.1 code

### ISSUE THREAD

**Issue by tissatussa** [LarsAur/Arcanum#11]
the v2.3.1 source code contains a small bug : i had to add `#include <stdint.h>` on top of `src/tuning/fengen.hpp` to fix the errors `‘uint8_t’ has not been declared` and `‘uint32_t’ has not been declared`.

[ i'm on Xubuntu 22.04 ]

**Comment by LarsAur** [comment]
Interesting. You are correct that it should be included in `fengen.hpp`, and I will fix it soon.

I am a bit curious as I am unable to recreate this error. 
Are you using the makefile to compile the program? If not, what command are you using?
Which compiler and compiler-version are you using? 

Thanks for submitting the issue :)

**Comment by tissatussa** [comment]
i used the Makefile.
but i changed the lines `CXX = g++` into `CXX = g++-13` and `LDFLAGS = -lpthread -lm -lstdc++ --static` into `LDFLAGS = -lpthread -lm` because i don't need the static build.

**Comment by LarsAur** [comment]
This should be fixed now. Thanks for reporting the issue :)
