### ISSUE TITLE
Missing dll files in Arcanum

### ISSUE THREAD

**Issue by GrahamCCRL** [LarsAur/Arcanum#2]
I'm hoping to include Arcanum in my Amateur Series, but it is missing dll files.

Graham (CCRL)

**Comment by LarsAur** [comment]
Thank you for checking out my project :)

Would you be able to provide me some details regarding your environment/system and what error message you get? Do you know which dll is missing?

**Comment by GrahamCCRL** [comment]
Hi Lars,

I use ChessGUI to run my events.
256mb hash per engine and 1 core.
Generic opening book.

At present, I could only test Arcanum without the SF net though, so perhaps
it's best for me to wait until you've trained your own NNUE.

The missing files are libstdc++-6.dll, libwinpthread-1.dll and
libgcc_s_seh-1.dii.

Regards,
Graham.

**Comment by LarsAur** [comment]
The non-nnue version is considerably worse than the nnue version. It is not too bad, but I have no official rating for it, so it is hard to say. Training my own nnue will probably happen in a distant future, at a point where i have more time. You can decide whether you want to wait or add the engine to the tournament based on this info.

**Comment by LarsAur** [comment]
Think the DLL issue should be solved by statically linking the libraries. Can you verify this by building it yourself or by testing the executable linked below?
[Arcanum_dev_build_static.zip](https://github.com/LarsAur/Arcanum/files/13419990/Arcanum_dev_build_static.zip)

**Comment by GrahamCCRL** [comment]
Yes - that exe works. :-)

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, May 9, 2024 at 10:15 AM
Subject: 108th Amateur Series Division 11
To: ammeraal ***@***.***>, Giuseppe Cannella <
***@***.***>


*108TH AMATEUR SERIES (Division 11)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion. Any other changes of
division will be at my discretion and may not necessarily involve playoff
matches.*

*Participants*

Arcanum 2.0 64-bit
Camel 1.5.1 64-bit *(new)*
Queen 4.05 64-bit *(2022-08)* *(relegated)*
Stellar 1.3.0 64-bit
Cinnamon 2.5 64-bit *(2022-07)*
InfraRed 2.0.2 64-bit
Tcheran 2.2 64-bit
Austerlitz 1.4.7 64-bit
chessplusplus 1.2.0 64-bit
Oxidation 0.6.2 64-bit
Trinket 3.0.0 64-bit
Maxwell 3.1-3 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE JOKER AND THE KNIGHT*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Ares 5.2.2 64-bit
4ku 5.0 64-bit
Vengeance 3.0.0 64-bit
Monty 1.0.0 64-bit
Elixir 2.0 64-bit
Arcanum 2.2 64-bit
Cheese 3.2.1 64-bit
KnightX 4.11 64-bit
Perseus dev ea813b9 64-bit
Rengar 2.0.0 64-bit
Stro4k 3.0 64-bit
Seawall 20231015 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16068

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16068
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/
