### ISSUE TITLE
NNUE usage

### ISSUE THREAD

**Issue by SzotsGabor** [LarsAur/Arcanum#4]
If the NNUE file is not present the engine crashes even if UseNNUE is false.

If it is present the engine plays OK but how can I check whether NNUE is indeed used or not?

Gabor Szots
CCRL testing group

**Comment by LarsAur** [comment]
Hi,

There is a custom UCI command called ```eval``` which returns/prints the static evaluation of the current position.
When NNUE is off, this should return 0 in the start position. When NNUE is on, it should return 42.
Let me know if this is enough for you to verify the NNUE usage. If not I will have to edit the code to handle not finding the .nnue files.

**Comment by SzotsGabor** [comment]
It would be enough but I think something is wrong. Here is my communication with the engine:

uci
id name Arcanum
id author Lars Murud Aurud
option name Hash type spin default 32 min 1 max 8196
option name ClearHash type button
option name UseNNUE type check default true
uciok
isready
readyok
position startpos
eval
42
setoption name UseNNUE value false
eval
42

As you can see, eval is 42 in both cases.

FYI, I played a short match between non-NNUE and NNUE and to my surprise non-NNUE won:

core of Arcanum 1.11 (no NNUE) 64-bit vs Arcanum 1.11 64-bit: 16 - 9 - 7 [0.609]
...      Arcanum 1.11 (no NNUE) 64-bit playing White: 7 - 6 - 3  [0.531] 16
...      Arcanum 1.11 (no NNUE) 64-bit playing Black: 9 - 3 - 4  [0.688] 16
...      White vs Black: 10 - 15 - 7  [0.422] 32
Elo difference: 77.2 +/- 112.4, LOS: 91.9 %, DrawRatio: 21.9 %
SPRT: llr 0 (0.0%), lbound -inf, ubound inf
32 of 32 games finished.

**Comment by LarsAur** [comment]
Ok, thank you for testing this. I think I have found the issue.
The `setoption` command does not consume the 'name' part of the command.
Seems like I had misunderstood the UCI spec. My current implementation works with the command `setoption UseNNUE value false`. 

I will will fix this so it works when using `setoption name UseNNUE value false`

**Comment by LarsAur** [comment]
This should be solved now. (I have not created a release yet)
* 'name' is consumed in `setoption name **** value ****`
* It will also default to using the non-nnue evaluation of the .nnue file is not found

**Comment by LarsAur** [comment]
This should be solved now. (I have not created a release yet)
* 'name' is consumed in `setoption name **** value ****`
* It will also default to using the non-nnue evaluation if the .nnue file is not found
