### ISSUE TITLE
Strength difference

### ISSUE THREAD

**Issue by SzotsGabor** [LarsAur/Arcanum#5]
Hi Lars,

In your estimation what is the difference in strength using-not using NNUE?

**Comment by LarsAur** [comment]
I have no rating for the non-nnue version. But I can give you some context:
- The last time i tested, the nnue-version was able to beat the non-nnue version in about ~95% of the games. (200ms per move)
- The non-nnue version was able to beat the 2700 Engine on chess.com. (3000ms per move) (I know this engine is not actually 2700 rated)

**Comment by SzotsGabor** [comment]
The reason I asked that is as follows:

Under the Cute Chess GUI I played a short match between the versions. TC was 30+0.2. After 37 games the score was tied. That seemed odd and somehow I thought that the non-NNUE version 'forgot' not to use NNUE. I can't tell you more at the moment.

EDIT: Brrr. The NNUE file was not present in the Arcanum folder. I have restored it, restarted the match and now it's OK.

**Comment by SzotsGabor** [comment]
FYI, I have started an Arcanum tournament for the CCRL blitz list.

EDIT: Already in the first game this struck me as surprising. I don't think Nxf7 was sound.

[Event "Arcanum 1.11.1 64-bit - Nov 22"]
[Site "Szentendre"]
[Date "2023.11.22"]
[Round "1"]
[White "Arcanum 1.11.1 (no NNUE) 64-bit"]
[Black "4ku 3.0 64-bit"]
[Result "0-1"]
[ECO "C42"]
[Opening "Russian-Three Knights Game, 4.Nxe5"]
[Time "15:21:22"]
[Variation "1.e4 e5"]
[TimeControl "85+1"]
[PlyCount "88"]

1. e4 e5 2. Nf3 Nf6 3. Nc3 Bb4 4. Nxe5 O-O 5. Be2 Re8 6. Nxf7 {+0.34/9 2}
Kxf7 {+1.43/20 3} 7. a3 {+0.36/9 2} Bxc3 {+1.75/21 3} 8. dxc3 {-0.57/9 2}
Rxe4 {+1.76/21 4} 9. O-O {-0.08/10 2} Nc6 {+1.82/21 3} 10. Bf3 {-0.11/10 2}
Re8 {+2.06/20 2} 11. Bg5 {-0.31/9 2} d6 {+2.16/20 3} 12. Re1 {-0.54/9 2}
Rxe1+ {+2.37/17 3} 13. Qxe1 {-0.37/10 2} h6 {+2.55/20 3} 14. Bd5+ {-0.78/9
2} Kf8 {+2.73/20 2} 15. Bxf6 {-1.03/11 2} Qxf6 {+2.78/22 7} 16. Qe2
{-1.32/10 2} Bd7 {+2.94/22 9} 17. Qb5 {-1.41/10 2} Rb8 {+2.97/21 9} 18. h3
{-1.73/9 2} Qf5 {+2.98/21 1} 19. Qd3 {-1.66/10 2} Re8 {+3.05/21 1} 20. b4
{-1.66/10 2} Qxd3 {+3.20/21 2} 21. cxd3 {-1.48/13 2} Re2 {+3.22/21 1} 22.
a4 {-1.65/11 2} Rc2 {+3.44/21 1} 23. b5 {-2.28/11 2} Na5 {+3.76/23 1} 24.
c4 {-2.43/11 2} Bf5 {+3.90/22 1} 25. Ra3 {-2.95/12 3} c6 {+4.38/23 2} 26.
Bf3 {-3.19/12 3} Rd2 {+4.46/23 2} 27. Be4 {-3.46/12 3} Bxe4 {+4.86/22 2}
28. dxe4 {-3.42/13 3} c5 {+4.86/22 1} 29. h4 {-3.52/12 3} Re2 {+5.14/20 1}
30. f3 {-3.50/13 3} Rc2 {+5.34/21 1} 31. Ra1 {-4.10/13 3} Nxc4 {+5.61/20 1}
32. Kh2 {-4.11/13 3} Ne3 {+5.82/21 1} 33. Kh3 {-4.28/13 3} Nxg2 {+5.96/19
1} 34. Rd1 {-4.28/13 3} Ke7 {+6.45/19 1} 35. Kg3 {-4.79/12 3} Ne3 {+6.69/21
2} 36. Rg1 {-5.01/13 3} Nc4 {+6.78/21 2} 37. Kf4 {-5.05/13 3} Kf6 {+7.03/21
1} 38. h5 {-6.10/13 4} Ra2 {+7.64/21 1} 39. Rd1 {-6.59/13 4} Rxa4 {+7.80/20
1} 40. Rc1 {-7.23/15 10} Ne5 {+8.04/22 1} 41. Rd1 {-6.94/14 5} Rd4
{+8.64/23 1} 42. Rg1 {-7.39/13 3} Rd3 {+10.27/23 2} 43. Rf1 {-8.34/13 2} c4
{+12.79/23 1} 44. Rg1 {+M0/1 0} Rxf3# {+M0/127 1} 0-1

[Event "Arcanum 1.11.1 64-bit - Nov 22"]
[Site "Szentendre"]
[Date "2023.11.22"]
[Round "1"]
[White "Arcanum 1.11.1 (no NNUE) 64-bit"]
[Black "Ceibo 0.9 64-bit"]
[Result "0-1"]
[ECO "A90"]
[Opening "Dutch"]
[Time "15:26:33"]
[Variation "2.c4 Nf6 3.g3 e6 5.Nf3 d5 6.O-O Bd6 7.b3"]
[TimeControl "85+1"]
[PlyCount "109"]

1. d4 f5 2. Nf3 Nf6 3. g3 e6 4. Bg2 d5 5. O-O Bd6 6. c4 c6 7. b3 Qe7 8. Nc3
{+0.64/9 2} O-O {-0.62/16 2} 9. Ne5 {+0.55/9 2} Nbd7 {-0.53/16 2} 10. f4
{+0.88/9 2} Ne4 {-0.50/18 2} 11. Qc2 {+0.61/9 2} Ndf6 {-0.49/16 2} 12. Bd2
{+0.69/8 2} Nxd2 {-0.27/18 2} 13. Qxd2 {+0.73/10 2} Bd7 {-0.19/17 2} 14. c5
{+0.65/9 2} Bc7 {-0.08/19 2} 15. b4 {+0.63/10 2} a5 {-0.10/19 2} 16. a3
{+0.66/9 2} Be8 {-0.09/19 2} 17. e3 {+0.26/9 2} Kh8 {-0.12/18 3} 18. Bf3
{+0.37/9 2} Ne4 {-0.01/15 3} 19. Qc2 {+0.60/10 2} Kg8 {-0.09/16 3} 20. Nxe4
{+0.55/9 2} fxe4 {-0.03/17 3} 21. Bg4 {+0.44/11 2} Bb8 {-0.10/17 3} 22.
bxa5 {+0.66/10 3} Rxa5 {-0.07/20 4} 23. Qc3 {+0.68/10 3} Ra8 {-0.09/22 3}
24. Rab1 {+0.69/11 3} Ra7 {-0.09/22 3} 25. Rf2 {+0.69/10 3} h6 {-0.12/19 3}
26. Ra2 {+0.79/10 3} Bxe5 {0.00/20 5} 27. dxe5 {+0.74/11 3} h5 {-0.09/18 3}
28. Bd1 {+0.86/11 3} g5 {-0.09/19 3} 29. a4 {+0.86/11 3} h4 {-0.02/17 3}
30. Bg4 {+0.88/10 3} Bg6 {0.00/19 3} 31. gxh4 {+0.86/10 3} gxf4 {+0.17/19
5} 32. exf4 {+0.92/10 3} Kh8 {+0.56/19 4} 33. h5 {+0.80/9 3} Bf5 {+0.65/18
2} 34. Bxf5 {+0.56/10 3} Rxf5 {+0.79/17 2} 35. Qe3 {+0.31/10 3} Rxh5
{+0.97/17 2} 36. a5 {+0.12/9 3} Qh4 {+0.98/19 2} 37. Qg3 {-0.38/10 4} Rh7
{+1.04/22 2} 38. Qxh4 {-0.41/12 4} Rxh4 {+1.06/21 2} 39. Rf1 {-0.29/13 4}
Kg8 {+1.13/21 2} 40. Ra3 {0.00/14 11} Kf7 {+1.10/22 2} 41. h3 {-0.23/13 6}
Rh5 {+1.46/21 2} 42. Kh2 {-0.39/12 3} Kg6 {+1.69/23 2} 43. Rg1+ {-0.43/12
2} Kf5 {+1.69/25 1} 44. Rg4 {-0.61/12 1} d4 {+1.65/25 1} 45. Kg3 {-0.78/12
1} e3 {+1.65/24 1} 46. Rg8 {-0.86/11 1} Ke4 {+1.65/22 1} 47. Ra2 {-0.87/11
1} Rh7 {+1.81/21 1} 48. h4 {-1.15/10 1} Rf7 {+2.00/20 1} 49. Rd8 {-1.37/11
1} Rg7+ {+3.07/19 1} 50. Kh2 {-2.20/11 0} Rg4 {+3.24/19 1} 51. h5 {-2.64/11
0} b5 {+4.89/18 2} 52. f5 {-5.31/9 1} Kf3 {+M7/28 2} 53. Rg8 {-M7/10 0}
Rxg8 {+M6/38 1} 54. Kh1 {-M6/1 0} e2 {+M5/59 1} 55. Ra3 {-M7/1 0  Arena
Adjudication} 0-1

**Comment by LarsAur** [comment]
Yeah, that does not look too good.
Unfortunately, I have seen it do similar moves before. I think it is because it thinks the opponent king is unsafe and overvalues the position. Thanks for giving me the PGN. I might look at fixing it in a later version.

I have some questions regarding the tournament which I was unable to find the answer to on your website.
* Do you not allow using NNUE? Or did you elect to disable NNUE for my engine because I use a pre-existing network generated by stockfish?
* Is there a way of seeing my engine play live? I found [ccrl.live](https://ccrl.live/16062), but I was unable to find out how to navigate the site. Is it possible to view other time controls or engines?

Thank you for taking your time to add my engine to your tournament :)

**Comment by SzotsGabor** [comment]
1. CCRL does allow NNUE. Many tested engines use NNUE and that's entirely fine with us. I myself also allow NNUE, I disable only the SF ones. That's my personal policy, and the reason is exactly what you guessed. I personally don't find it interesting to test such engines. On our list you can find Coiled (no NNUE) with which I did the same. And there were engines which I did not test at all for the same reason. The only exception I made was with BBC 1.4 a couple of years ago when NNUE was new to me and I was simply curious how much strength can be gained by using an SF net instead of traditional evaluation.
I could as well say I would like to encourage authors to develop their own unique nets (or stick with HCE). Of course using an SF net could be a step in that direction but I would rather skip that step in my testing.

2. I do not broadcast my tournaments. Graham does but I don't know the details or technicalities. I suggest you contact him directly.

**Comment by LarsAur** [comment]
This seems like a fair policy and is what I guessed would be the reasoning. Maybe this will inspire me to continue working on my HCE.

Edit: Feel free to open new issues if there are more inquiries, I'll close this one for now.

Thanks again :)
